//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuPortalWebservice.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.NuPortalServiceSoap")]
    public interface NuPortalServiceSoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginInfo", ReplyAction="*")]
        NuPortalWebservice.ServiceReference1.LoginInfoResponse LoginInfo(NuPortalWebservice.ServiceReference1.LoginInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<NuPortalWebservice.ServiceReference1.LoginInfoResponse> LoginInfoAsync(NuPortalWebservice.ServiceReference1.LoginInfoRequest request);
        
        // CODEGEN: Generating message contract since element name FirstName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmployee", ReplyAction="*")]
        NuPortalWebservice.ServiceReference1.CreateEmployeeResponse CreateEmployee(NuPortalWebservice.ServiceReference1.CreateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<NuPortalWebservice.ServiceReference1.CreateEmployeeResponse> CreateEmployeeAsync(NuPortalWebservice.ServiceReference1.CreateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name Address1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPersonalInfo", ReplyAction="*")]
        NuPortalWebservice.ServiceReference1.SetPersonalInfoResponse SetPersonalInfo(NuPortalWebservice.ServiceReference1.SetPersonalInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPersonalInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<NuPortalWebservice.ServiceReference1.SetPersonalInfoResponse> SetPersonalInfoAsync(NuPortalWebservice.ServiceReference1.SetPersonalInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginInfo", Namespace="http://tempuri.org/", Order=0)]
        public NuPortalWebservice.ServiceReference1.LoginInfoRequestBody Body;
        
        public LoginInfoRequest() {
        }
        
        public LoginInfoRequest(NuPortalWebservice.ServiceReference1.LoginInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginInfoRequestBody() {
        }
        
        public LoginInfoRequestBody(string UserName, string Password) {
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public NuPortalWebservice.ServiceReference1.LoginInfoResponseBody Body;
        
        public LoginInfoResponse() {
        }
        
        public LoginInfoResponse(NuPortalWebservice.ServiceReference1.LoginInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginInfoResult;
        
        public LoginInfoResponseBody() {
        }
        
        public LoginInfoResponseBody(string LoginInfoResult) {
            this.LoginInfoResult = LoginInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmployee", Namespace="http://tempuri.org/", Order=0)]
        public NuPortalWebservice.ServiceReference1.CreateEmployeeRequestBody Body;
        
        public CreateEmployeeRequest() {
        }
        
        public CreateEmployeeRequest(NuPortalWebservice.ServiceReference1.CreateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FirstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmployeeCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int JobTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Manager;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ProfilePicUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string QuotesPictureUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string BackGroundPicUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.DateTime HireDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.DateTime ConfirmationDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string WorkEMail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string OfficeLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string WorkLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int EmptTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string RelievingDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public int CompanyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public System.DateTime CreatedDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public System.DateTime ModifiedDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public int CreatedEmpId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public int ModifiedEmpId;
        
        public CreateEmployeeRequestBody() {
        }
        
        public CreateEmployeeRequestBody(
                    string FirstName, 
                    string LastName, 
                    string Title, 
                    string EmployeeCode, 
                    int JobTitle, 
                    string Manager, 
                    string ProfilePicUrl, 
                    string QuotesPictureUrl, 
                    string BackGroundPicUrl, 
                    System.DateTime HireDate, 
                    System.DateTime ConfirmationDate, 
                    string WorkEMail, 
                    string OfficeLocation, 
                    string WorkLocation, 
                    int EmptTypeId, 
                    string RelievingDate, 
                    int CompanyId, 
                    System.DateTime CreatedDate, 
                    System.DateTime ModifiedDate, 
                    int CreatedEmpId, 
                    int ModifiedEmpId) {
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Title = Title;
            this.EmployeeCode = EmployeeCode;
            this.JobTitle = JobTitle;
            this.Manager = Manager;
            this.ProfilePicUrl = ProfilePicUrl;
            this.QuotesPictureUrl = QuotesPictureUrl;
            this.BackGroundPicUrl = BackGroundPicUrl;
            this.HireDate = HireDate;
            this.ConfirmationDate = ConfirmationDate;
            this.WorkEMail = WorkEMail;
            this.OfficeLocation = OfficeLocation;
            this.WorkLocation = WorkLocation;
            this.EmptTypeId = EmptTypeId;
            this.RelievingDate = RelievingDate;
            this.CompanyId = CompanyId;
            this.CreatedDate = CreatedDate;
            this.ModifiedDate = ModifiedDate;
            this.CreatedEmpId = CreatedEmpId;
            this.ModifiedEmpId = ModifiedEmpId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public NuPortalWebservice.ServiceReference1.CreateEmployeeResponseBody Body;
        
        public CreateEmployeeResponse() {
        }
        
        public CreateEmployeeResponse(NuPortalWebservice.ServiceReference1.CreateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateEmployeeResult;
        
        public CreateEmployeeResponseBody() {
        }
        
        public CreateEmployeeResponseBody(bool CreateEmployeeResult) {
            this.CreateEmployeeResult = CreateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPersonalInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPersonalInfo", Namespace="http://tempuri.org/", Order=0)]
        public NuPortalWebservice.ServiceReference1.SetPersonalInfoRequestBody Body;
        
        public SetPersonalInfoRequest() {
        }
        
        public SetPersonalInfoRequest(NuPortalWebservice.ServiceReference1.SetPersonalInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetPersonalInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int EmpId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string City1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string State1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Country1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ZipCode1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Phone1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Address2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string City2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string State2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Country2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ZipCode2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Phone2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string EmergencyPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string EmailId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string DOB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Nationality;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string BloodGroup;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public System.DateTime CreatedDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public System.DateTime ModifiedDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public int CreatedEmpId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public int ModifiedEmpId;
        
        public SetPersonalInfoRequestBody() {
        }
        
        public SetPersonalInfoRequestBody(
                    int EmpId, 
                    string Address1, 
                    string City1, 
                    string State1, 
                    string Country1, 
                    string ZipCode1, 
                    string Phone1, 
                    string Address2, 
                    string City2, 
                    string State2, 
                    string Country2, 
                    string ZipCode2, 
                    string Phone2, 
                    string EmergencyPhone, 
                    string EmailId, 
                    string DOB, 
                    string Gender, 
                    string Nationality, 
                    string BloodGroup, 
                    System.DateTime CreatedDate, 
                    System.DateTime ModifiedDate, 
                    int CreatedEmpId, 
                    int ModifiedEmpId) {
            this.EmpId = EmpId;
            this.Address1 = Address1;
            this.City1 = City1;
            this.State1 = State1;
            this.Country1 = Country1;
            this.ZipCode1 = ZipCode1;
            this.Phone1 = Phone1;
            this.Address2 = Address2;
            this.City2 = City2;
            this.State2 = State2;
            this.Country2 = Country2;
            this.ZipCode2 = ZipCode2;
            this.Phone2 = Phone2;
            this.EmergencyPhone = EmergencyPhone;
            this.EmailId = EmailId;
            this.DOB = DOB;
            this.Gender = Gender;
            this.Nationality = Nationality;
            this.BloodGroup = BloodGroup;
            this.CreatedDate = CreatedDate;
            this.ModifiedDate = ModifiedDate;
            this.CreatedEmpId = CreatedEmpId;
            this.ModifiedEmpId = ModifiedEmpId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPersonalInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPersonalInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public NuPortalWebservice.ServiceReference1.SetPersonalInfoResponseBody Body;
        
        public SetPersonalInfoResponse() {
        }
        
        public SetPersonalInfoResponse(NuPortalWebservice.ServiceReference1.SetPersonalInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetPersonalInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetPersonalInfoResult;
        
        public SetPersonalInfoResponseBody() {
        }
        
        public SetPersonalInfoResponseBody(bool SetPersonalInfoResult) {
            this.SetPersonalInfoResult = SetPersonalInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NuPortalServiceSoapChannel : NuPortalWebservice.ServiceReference1.NuPortalServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NuPortalServiceSoapClient : System.ServiceModel.ClientBase<NuPortalWebservice.ServiceReference1.NuPortalServiceSoap>, NuPortalWebservice.ServiceReference1.NuPortalServiceSoap {
        
        public NuPortalServiceSoapClient() {
        }
        
        public NuPortalServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NuPortalServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NuPortalServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NuPortalServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NuPortalWebservice.ServiceReference1.LoginInfoResponse NuPortalWebservice.ServiceReference1.NuPortalServiceSoap.LoginInfo(NuPortalWebservice.ServiceReference1.LoginInfoRequest request) {
            return base.Channel.LoginInfo(request);
        }
        
        public string LoginInfo(string UserName, string Password) {
            NuPortalWebservice.ServiceReference1.LoginInfoRequest inValue = new NuPortalWebservice.ServiceReference1.LoginInfoRequest();
            inValue.Body = new NuPortalWebservice.ServiceReference1.LoginInfoRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            NuPortalWebservice.ServiceReference1.LoginInfoResponse retVal = ((NuPortalWebservice.ServiceReference1.NuPortalServiceSoap)(this)).LoginInfo(inValue);
            return retVal.Body.LoginInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NuPortalWebservice.ServiceReference1.LoginInfoResponse> NuPortalWebservice.ServiceReference1.NuPortalServiceSoap.LoginInfoAsync(NuPortalWebservice.ServiceReference1.LoginInfoRequest request) {
            return base.Channel.LoginInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NuPortalWebservice.ServiceReference1.LoginInfoResponse> LoginInfoAsync(string UserName, string Password) {
            NuPortalWebservice.ServiceReference1.LoginInfoRequest inValue = new NuPortalWebservice.ServiceReference1.LoginInfoRequest();
            inValue.Body = new NuPortalWebservice.ServiceReference1.LoginInfoRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            return ((NuPortalWebservice.ServiceReference1.NuPortalServiceSoap)(this)).LoginInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NuPortalWebservice.ServiceReference1.CreateEmployeeResponse NuPortalWebservice.ServiceReference1.NuPortalServiceSoap.CreateEmployee(NuPortalWebservice.ServiceReference1.CreateEmployeeRequest request) {
            return base.Channel.CreateEmployee(request);
        }
        
        public bool CreateEmployee(
                    string FirstName, 
                    string LastName, 
                    string Title, 
                    string EmployeeCode, 
                    int JobTitle, 
                    string Manager, 
                    string ProfilePicUrl, 
                    string QuotesPictureUrl, 
                    string BackGroundPicUrl, 
                    System.DateTime HireDate, 
                    System.DateTime ConfirmationDate, 
                    string WorkEMail, 
                    string OfficeLocation, 
                    string WorkLocation, 
                    int EmptTypeId, 
                    string RelievingDate, 
                    int CompanyId, 
                    System.DateTime CreatedDate, 
                    System.DateTime ModifiedDate, 
                    int CreatedEmpId, 
                    int ModifiedEmpId) {
            NuPortalWebservice.ServiceReference1.CreateEmployeeRequest inValue = new NuPortalWebservice.ServiceReference1.CreateEmployeeRequest();
            inValue.Body = new NuPortalWebservice.ServiceReference1.CreateEmployeeRequestBody();
            inValue.Body.FirstName = FirstName;
            inValue.Body.LastName = LastName;
            inValue.Body.Title = Title;
            inValue.Body.EmployeeCode = EmployeeCode;
            inValue.Body.JobTitle = JobTitle;
            inValue.Body.Manager = Manager;
            inValue.Body.ProfilePicUrl = ProfilePicUrl;
            inValue.Body.QuotesPictureUrl = QuotesPictureUrl;
            inValue.Body.BackGroundPicUrl = BackGroundPicUrl;
            inValue.Body.HireDate = HireDate;
            inValue.Body.ConfirmationDate = ConfirmationDate;
            inValue.Body.WorkEMail = WorkEMail;
            inValue.Body.OfficeLocation = OfficeLocation;
            inValue.Body.WorkLocation = WorkLocation;
            inValue.Body.EmptTypeId = EmptTypeId;
            inValue.Body.RelievingDate = RelievingDate;
            inValue.Body.CompanyId = CompanyId;
            inValue.Body.CreatedDate = CreatedDate;
            inValue.Body.ModifiedDate = ModifiedDate;
            inValue.Body.CreatedEmpId = CreatedEmpId;
            inValue.Body.ModifiedEmpId = ModifiedEmpId;
            NuPortalWebservice.ServiceReference1.CreateEmployeeResponse retVal = ((NuPortalWebservice.ServiceReference1.NuPortalServiceSoap)(this)).CreateEmployee(inValue);
            return retVal.Body.CreateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NuPortalWebservice.ServiceReference1.CreateEmployeeResponse> NuPortalWebservice.ServiceReference1.NuPortalServiceSoap.CreateEmployeeAsync(NuPortalWebservice.ServiceReference1.CreateEmployeeRequest request) {
            return base.Channel.CreateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<NuPortalWebservice.ServiceReference1.CreateEmployeeResponse> CreateEmployeeAsync(
                    string FirstName, 
                    string LastName, 
                    string Title, 
                    string EmployeeCode, 
                    int JobTitle, 
                    string Manager, 
                    string ProfilePicUrl, 
                    string QuotesPictureUrl, 
                    string BackGroundPicUrl, 
                    System.DateTime HireDate, 
                    System.DateTime ConfirmationDate, 
                    string WorkEMail, 
                    string OfficeLocation, 
                    string WorkLocation, 
                    int EmptTypeId, 
                    string RelievingDate, 
                    int CompanyId, 
                    System.DateTime CreatedDate, 
                    System.DateTime ModifiedDate, 
                    int CreatedEmpId, 
                    int ModifiedEmpId) {
            NuPortalWebservice.ServiceReference1.CreateEmployeeRequest inValue = new NuPortalWebservice.ServiceReference1.CreateEmployeeRequest();
            inValue.Body = new NuPortalWebservice.ServiceReference1.CreateEmployeeRequestBody();
            inValue.Body.FirstName = FirstName;
            inValue.Body.LastName = LastName;
            inValue.Body.Title = Title;
            inValue.Body.EmployeeCode = EmployeeCode;
            inValue.Body.JobTitle = JobTitle;
            inValue.Body.Manager = Manager;
            inValue.Body.ProfilePicUrl = ProfilePicUrl;
            inValue.Body.QuotesPictureUrl = QuotesPictureUrl;
            inValue.Body.BackGroundPicUrl = BackGroundPicUrl;
            inValue.Body.HireDate = HireDate;
            inValue.Body.ConfirmationDate = ConfirmationDate;
            inValue.Body.WorkEMail = WorkEMail;
            inValue.Body.OfficeLocation = OfficeLocation;
            inValue.Body.WorkLocation = WorkLocation;
            inValue.Body.EmptTypeId = EmptTypeId;
            inValue.Body.RelievingDate = RelievingDate;
            inValue.Body.CompanyId = CompanyId;
            inValue.Body.CreatedDate = CreatedDate;
            inValue.Body.ModifiedDate = ModifiedDate;
            inValue.Body.CreatedEmpId = CreatedEmpId;
            inValue.Body.ModifiedEmpId = ModifiedEmpId;
            return ((NuPortalWebservice.ServiceReference1.NuPortalServiceSoap)(this)).CreateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NuPortalWebservice.ServiceReference1.SetPersonalInfoResponse NuPortalWebservice.ServiceReference1.NuPortalServiceSoap.SetPersonalInfo(NuPortalWebservice.ServiceReference1.SetPersonalInfoRequest request) {
            return base.Channel.SetPersonalInfo(request);
        }
        
        public bool SetPersonalInfo(
                    int EmpId, 
                    string Address1, 
                    string City1, 
                    string State1, 
                    string Country1, 
                    string ZipCode1, 
                    string Phone1, 
                    string Address2, 
                    string City2, 
                    string State2, 
                    string Country2, 
                    string ZipCode2, 
                    string Phone2, 
                    string EmergencyPhone, 
                    string EmailId, 
                    string DOB, 
                    string Gender, 
                    string Nationality, 
                    string BloodGroup, 
                    System.DateTime CreatedDate, 
                    System.DateTime ModifiedDate, 
                    int CreatedEmpId, 
                    int ModifiedEmpId) {
            NuPortalWebservice.ServiceReference1.SetPersonalInfoRequest inValue = new NuPortalWebservice.ServiceReference1.SetPersonalInfoRequest();
            inValue.Body = new NuPortalWebservice.ServiceReference1.SetPersonalInfoRequestBody();
            inValue.Body.EmpId = EmpId;
            inValue.Body.Address1 = Address1;
            inValue.Body.City1 = City1;
            inValue.Body.State1 = State1;
            inValue.Body.Country1 = Country1;
            inValue.Body.ZipCode1 = ZipCode1;
            inValue.Body.Phone1 = Phone1;
            inValue.Body.Address2 = Address2;
            inValue.Body.City2 = City2;
            inValue.Body.State2 = State2;
            inValue.Body.Country2 = Country2;
            inValue.Body.ZipCode2 = ZipCode2;
            inValue.Body.Phone2 = Phone2;
            inValue.Body.EmergencyPhone = EmergencyPhone;
            inValue.Body.EmailId = EmailId;
            inValue.Body.DOB = DOB;
            inValue.Body.Gender = Gender;
            inValue.Body.Nationality = Nationality;
            inValue.Body.BloodGroup = BloodGroup;
            inValue.Body.CreatedDate = CreatedDate;
            inValue.Body.ModifiedDate = ModifiedDate;
            inValue.Body.CreatedEmpId = CreatedEmpId;
            inValue.Body.ModifiedEmpId = ModifiedEmpId;
            NuPortalWebservice.ServiceReference1.SetPersonalInfoResponse retVal = ((NuPortalWebservice.ServiceReference1.NuPortalServiceSoap)(this)).SetPersonalInfo(inValue);
            return retVal.Body.SetPersonalInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NuPortalWebservice.ServiceReference1.SetPersonalInfoResponse> NuPortalWebservice.ServiceReference1.NuPortalServiceSoap.SetPersonalInfoAsync(NuPortalWebservice.ServiceReference1.SetPersonalInfoRequest request) {
            return base.Channel.SetPersonalInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NuPortalWebservice.ServiceReference1.SetPersonalInfoResponse> SetPersonalInfoAsync(
                    int EmpId, 
                    string Address1, 
                    string City1, 
                    string State1, 
                    string Country1, 
                    string ZipCode1, 
                    string Phone1, 
                    string Address2, 
                    string City2, 
                    string State2, 
                    string Country2, 
                    string ZipCode2, 
                    string Phone2, 
                    string EmergencyPhone, 
                    string EmailId, 
                    string DOB, 
                    string Gender, 
                    string Nationality, 
                    string BloodGroup, 
                    System.DateTime CreatedDate, 
                    System.DateTime ModifiedDate, 
                    int CreatedEmpId, 
                    int ModifiedEmpId) {
            NuPortalWebservice.ServiceReference1.SetPersonalInfoRequest inValue = new NuPortalWebservice.ServiceReference1.SetPersonalInfoRequest();
            inValue.Body = new NuPortalWebservice.ServiceReference1.SetPersonalInfoRequestBody();
            inValue.Body.EmpId = EmpId;
            inValue.Body.Address1 = Address1;
            inValue.Body.City1 = City1;
            inValue.Body.State1 = State1;
            inValue.Body.Country1 = Country1;
            inValue.Body.ZipCode1 = ZipCode1;
            inValue.Body.Phone1 = Phone1;
            inValue.Body.Address2 = Address2;
            inValue.Body.City2 = City2;
            inValue.Body.State2 = State2;
            inValue.Body.Country2 = Country2;
            inValue.Body.ZipCode2 = ZipCode2;
            inValue.Body.Phone2 = Phone2;
            inValue.Body.EmergencyPhone = EmergencyPhone;
            inValue.Body.EmailId = EmailId;
            inValue.Body.DOB = DOB;
            inValue.Body.Gender = Gender;
            inValue.Body.Nationality = Nationality;
            inValue.Body.BloodGroup = BloodGroup;
            inValue.Body.CreatedDate = CreatedDate;
            inValue.Body.ModifiedDate = ModifiedDate;
            inValue.Body.CreatedEmpId = CreatedEmpId;
            inValue.Body.ModifiedEmpId = ModifiedEmpId;
            return ((NuPortalWebservice.ServiceReference1.NuPortalServiceSoap)(this)).SetPersonalInfoAsync(inValue);
        }
    }
}
